# Explanation 


```
[[2 5 6]
 [8 0 6]
 [4 3 2]
 [4 3 2]]
```
First house's possible material costs are `[2, 5, 6]`
So if we would have only one house we would choose the material with min cost. The second house is `[8 0 6]`. Now for every position we need to find the releation with previous one:

Index 0:

`8 + 2` is not possible since it's been restricted.

`8 + 5 = 13`

`8 + 6 = 14`

So for index 0 we have `[13, 14]`

Index 1:

`0 + 2 = 2` 

`0 + 5` restricted

`0 + 6 = 6`

So for index 1 we have = `[2, 6]`

Index 2:

`6 + 2 = 8`

`6 + 0 = 6`

`6 + 6` restricted

So for index 2 we have `[8, 6]`

So say if we have a dictionary and set the cost for every material to zero we would had: dic = `{0: [0], 1: [0], 2: [0]}`

After first house our dictionary would be `{0: [2], 1: [5], 2: [6]}`. For third (or any next house) we would slect minimum of the costs from unrestricted costs.

After second house our dictionary is: `{0: [13, 14], 1: [2, 6], 2: [8, 6]}`

So now again to pass to next house we choose the minimum of path cost to this house becouse in either way we would get to current house and would not happen any collision of materials, it's very obvious that we should choose the path with least cost.

# And if you have further questions you can reach me here:
# farhad.szd@gmail.com
# +994 55 736 7002 (WhatsApp)
# farhad_zada_ (instagram)

In [13]:
# hackerrank.com // Construction Managment 

"""                                                 WARNING                                                  """
'''To understand it you should read both the code and comments at least twice, cuz it actually works backward'''

# We need a dictionary that keys are indices and values are lists so we use defaultdict set to list

from collections import defaultdict
import numpy as np
# Here I put an example of data. You can change it to the real task by remowing 'rows' 
# variable and putting the real data variable from question into the function (min_cost()).


rows = np.random.randint(10, size = (4, 3)) # Here we generate some random numbers

#for example: 
# [[2 5 6]
#  [8 0 6]
#  [4 3 2]
#  [4 3 2]]

print(rows)

def min_cost(houses):

    generator = defaultdict(list) # We will use this dictionary to save results after each loop over a house
    for i in range(len(houses[0])): generator[i].append(0) # Set the default cost to 0 for all choices

    for house in houses:
        tmp = defaultdict(list) # Define another dictionary 'temporarry' since it is changing for every new house

        for restricted, material in enumerate(house): # Here we iterate over values of the house and by restricted we know that with wich previous value we can't sum it

            for k, v in generator.items(): # Here we 

                if k != restricted: # If the index of current material is not the same with previous one
                    tmp[restricted].append(material+min(v)) # Here we use tmp, into our current material's index we append
                                                          # all the values that are possible since here, but we select min( of values) since if that is not we don't need that values
        
        generator = tmp # Now our temporary dict 'tmp' carries the value till current house then we replace generator to tmp

    return min([min(val) for val in generator.values()]) # And now we choose the minimum path

min_cost(rows)

# I recommend you to use print() in every point to get the real sense how it works. 


[[2 5 6]
 [8 0 6]
 [4 3 2]
 [4 3 2]]


7

In [ ]:
# /// Real question solution ///

from collections import defaultdict

def min_cost(houses):

    generator = defaultdict(list)
    for i in range(3): generator[i].append(0)

    for house in houses:
        tmp = defaultdict(list)
        for restricted, material in enumerate(house):
            for k, v in generator.items():
                if k != restricted:
                    tmp[restricted].append(material+min(v)) 
        generator = tmp

    return min([min(val) for val in generator.values()])

print(min_cost(cost))